# Load Dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

os.listdir('/content/drive/MyDrive')

['Job Market Project',
 'Classroom',
 'Untitled document (46).gdoc',
 '20200315_081622.jpg',
 'Copy of Aditi Raj - DIAGNOSTIC1_Periodic classification of elements.docx',
 'Untitled document (45).gdoc',
 'Untitled spreadsheet (18).gsheet',
 '20200317_093543.jpg',
 '20200318_172805.jpg',
 '20200319_095450.jpg',
 'Untitled document (44).gdoc',
 '20200406_075808.jpg',
 '06-Apr-2020 7:58:58 AM.jpeg',
 '06-Apr-2020 7:59:25 AM.jpeg',
 'Aditi Raj - Activity Gr 10 (3).docx',
 'Copy of AS- Worksheet 1- Questions.gdoc',
 'RAC GRADE10 MODULE 6 nonfiction-reading-test-carnivorous-plants (1).gdoc',
 'RAC GRADE10 MODULE 6 nonfiction-reading-test-carnivorous-plants.gdoc',
 'IMG-20200414-WA0083.jpg',
 'Aditi Raj - Activity Gr 10 (2).docx',
 'Q6 Parts of a Flower.jpg',
 'Gr 10 MA Timeline.gdoc',
 '1. Periodic Classification of Elements',
 '2. Chemical reaction and Equations',
 'Diagnostic Test Metals&NonM.jpg',
 '3. Metals & Non-Metals',
 'Copy of GR 10-HTML NOTES.docx',
 '20200505_094702.jpg',
 '20200505_094646.jpg',
 '20200505_094635.jpg',
 'IMG-20200414-WA0055.jpg',
 'Untitled Jam.pdf',
 'Untitled document (43).gdoc',
 'Harihar kaka Assignment extra ques.gdoc',
 'English May 10 PPT.gdoc',
 'Physics May 12 PPT.gdoc',
 'Biology May 12 PPT.gdoc',
 'Untitled document (42).gdoc',
 'Untitled document (41).gdoc',
 'English 13 May PPT.gdoc',
 'module 1(2).pdf',
 'module 1(2) (1).gdoc',
 'module 1(2).gdoc',
 'Physics May 14 PPT.gdoc',
 'Untitled form (2).gform',
 'Eng 17 May PPT.gdoc',
 'AditiRaj-10g-SelfAssessment-ClassTest-Maths-17May.pdf',
 '20200503_110455.jpg',
 '20200503_110457.jpg',
 '20200503_105936.jpg',
 '20200503_110450.jpg',
 '20200503_110722.jpg',
 '20200503_110709.jpg',
 '20200503_110831.jpg',
 '20200503_110837.jpg',
 '20200503_111233.jpg',
 '20200503_111222.jpg',
 '20200503_111518.jpg',
 '20200503_112017.jpg',
 '20200503_112113.jpg',
 '20200503_112141.jpg',
 '20200503_112350.jpg',
 '20200503_112248.jpg',
 '20200503_112403.jpg',
 'Untitled document (40).gdoc',
 'Chem May 17 & 18 PPT.gdoc',
 'Hindi 18 May PPT.gdoc',
 'Bio May 19 PPT.gdoc',
 'Bio May 20 PPT.gdoc',
 'Eng May 20 PPT.gdoc',
 'Money And Credit LO May 21.gdoc',
 'Untitled form (1).gform',
 'Bio May 21 PPT.gdoc',
 'Class notes.gdoc',
 'ActivityBioMay27.jpg',
 'Bio May 27 PPT.gdoc',
 'Phy May 27 PPT.gdoc',
 'Eng May 27 PPT.gdoc',
 'Untitled document (39).gdoc',
 'Comp May 28 PPT.gdoc',
 'AditiRaj-10g-MepMA.pdf',
 'Forms - html.gdoc',
 'Bio May 31 PPT.gdoc',
 'Chem June 1 PPT.gdoc',
 'Untitled document (38).gdoc',
 'Hindi May 19 PPT.gdoc',
 'Chem June 3 PPT.gdoc',
 'Untitled document (37).gdoc',
 'Copy of MAG enrichment.gdoc',
 'Eng June 1 & 2 PPT.gdoc',
 'Untitled document (36).gdoc',
 'Upper body circuit training.gslides',
 'Phy June 7 PPT & Notes.gdoc',
 'Bio Class before June  7 PPT.gdoc',
 'Hin June 7 PPT.gdoc',
 'SCIENTIFIC ENQUIRY-Aditi Raj (1).gdoc',
 'June 9.png',
 'Bio June 10 PPT.gdoc',
 'Bio Revision.jpg',
 'Eng June 8 & 10 Eng PPT & Notes.gdoc',
 'Hindi June 8 PPT.gdoc',
 'Eng June 11 PPT-Preposition .gdoc',
 'Comp June 11 PPT.gdoc',
 '10-6-2020 In triangle ABC.gdoc',
 'Aditiraj-10g-Worksheet-Phy-June15.pdf',
 'Eng June 15 PPT.gdoc',
 'Hin June 15 PPT Revision Harihar Kaka.gdoc',
 'Untitled document (35).gdoc',
 'Complementary angles (2).gdoc',
 'Complementary angles (1).gdoc',
 'Complementary angles.gdoc',
 'Bio June 17 PPT.gdoc',
 'CamScanner 06-17-2020 09.57.25.gdoc',
 'Domestic electric circuit (1).gslides',
 'Domestic electric circuit.gslides',
 'Phy June 17 PPT.gdoc',
 'Untitled document (34).gdoc',
 'Chem June 18 PPT.gdoc',
 'flower-border-art-153476-5009359.jpg',
 'Untitled presentation (3).gslides',
 'Chem June 22 PPT.gdoc',
 'Mep June 22 PPT.gdoc',
 'Hindi June 22 PPT.gdoc',
 'Chem June 24 PPT.gdoc',
 'As Session 24 June.jpg',
 'Photo_1593169076866.png',
 '1593166054595.png',
 'Bio June 28 PPT.gdoc',
 'AS TRIGONOMETRY (1).gdoc',
 'AS TRIGONOMETRY.gdoc',
 'Hindi June 28 PPT.gdoc',
 'Aditiraj-10g-Maths-AS-28June.pdf',
 'Aditiraj-10g-AS-Physics-29June.pdf',
 'Eng June 29 PPT.gdoc',
 'Hindi 29 June PPT .gdoc',
 'Bio June 30 PPT.gdoc',
 'Eng 30 June PPT.gdoc',
 'MA 2 - CONCEPT MAP - ANNE FRANK -  GRADE 10 (1).gdoc',
 'MA 2 - CONCEPT MAP - ANNE FRANK -  GRADE 10.gdoc',
 'Hin 2 July.gdoc',
 'SC Social 12 July 2nd Period.gdoc',
 'SC Phy 12 July 3nd Period.gdoc',
 'SC Social 13 July 1st Period.gdoc',
 'SC Bio 14 July 1st Period.gdoc',
 'SC Social 14 July 3rd Period.gdoc',
 'SC Social 15 July 2nd Period.gdoc',
 'SC Chem 15 July 3rd Period.gdoc',
 'SC Social 16 July 1st Period.gdoc',
 'Untitled form.gform',
 'SC Social 19 July 2nd Period.gdoc',
 'SC Chem 19 July 4th Period.gdoc',
 'SC Social 20 July 1st Period.gdoc',
 'SC Phy 20 July 4th Period.gdoc',
 'SC Bio 21 July 1st Period.gdoc',
 'SC Social 21 July 3rd Period.gdoc',
 'SC Comp 21 July 4th Period.gdoc',
 'SC Bio 15 July 4th Period.gdoc',
 'SC Social 22 July 2nd Period.gdoc',
 'SC Bio 22 July 4th Period.gdoc',
 'Class1 Form (3).gslides',
 'SC Social 23 July 1st Period.gdoc',
 'SC Comp 23 July 3rd Period.gdoc',
 'Class1 Form (2).gslides',
 'Class1 Form (1).gslides',
 'Class1 Form.gslides',
 'Untitled document (33).gdoc',
 'SC Social 26 July 3rd Period.gdoc',
 'SC Social 27 July 2nd Period.gdoc',
 'Untitled document (32).gdoc',
 'SC Social 28 July 2nd Period.gdoc',
 'SC Hindi 29 July 1st Period.gdoc',
 'Character Elements.pdf',
 'Teen Quote',
 'Sleep Quote',
 'Untitled document (31).gdoc',
 'Untitled document (30).gdoc',
 'SC Bio Revision 3 Aug.pdf',
 'SC Phy 4 Aug 3rd Period.gdoc',
 'WP.gdoc',
 'Chem May 10 PPT.gdoc',
 'SC Social 6 Aug 1st Period Map Test.gdoc',
 'Session 1 Hindi Model Lesson Planning of Day 1 Period 1 Notice Writing (1).gslides',
 'Session 1 Hindi Model Lesson Planning of Day 1 Period 1 Notice Writing.gslides',
 'GR 10-HTML NOTES.gdoc',
 'Gr 10_Project guidelines_20-21.gdoc',
 'MEP SUMMER PROJECT.gdoc',
 'Hindi 1st Period 9 Sep.gdoc',
 'Social 2nd Period 9 Sep.gdoc',
 'Bio 3rd Period 9 Sep.gdoc',
 'Phy 4th Period 9 Sep.gdoc',
 'DC Flowchart.jpg',
 'Pathways of glucose breakdown.jpg',
 '16001678612368931347598555567749.jpg',
 'Untitled document (29).gdoc',
 'SG.jpg (500×369)',
 'SG 2.jpg (800×1000)',
 'Ans.pdf',
 'Ans 1.jpg',
 'Hive.jpg',
 'HP1.jpg',
 'HP2.jpg',
 'HP3.jpg',
 'Untitled document (28).gdoc',
 'A1.jpg',
 'A2.jpg',
 'Sky.jpg',
 'Ephoto360.com_15f70ce8caf1e7.jpg',
 'Ephoto360.com_15f70ce5cd9001.jpg',
 'Ephoto360.com_15f70ce78a8410.jpg',
 'Ephoto360.com_15f70cead018ce.jpg',
 'Ephoto360.com_15f70cec610fac.jpg',
 'YOGA POSES FOR ABS .gslides',
 'Untitled document (27).gdoc',
 'SCIENTIFIC ENQUIRY-Aditi Raj.gdoc',
 '16020714959578052362535461875178.jpg',
 '1602071757342434515686682593663.jpg',
 'SKY_20201004_172245_.jpg',
 'SKY_20200928_145339_.jpg',
 'Aditi Raj-12 Oct-Social-Revision Ques.pdf',
 'Untitled document (26).gdoc',
 'Aditi Raj-13 Oct-Math Test.pdf',
 'Consumers Project.pdf',
 'Aditi Raj-14 Oct-Math-MockTest.pdf',
 'MEP PT 2.pdf',
 'Aditi Raj-MEP PT 2-Oct 15.pdf',
 'Phy May 31 PPT.gdoc',
 'Copy of Series Combination of Resistances- PPT (1).gslides',
 'Copy of Series Combination of Resistances- PPT.gslides',
 'Copy of Resistivity modified.gslides',
 'Copy of DL-PHY-MODULE 7- RESISTORS IN PARALLEL (1).gslides',
 'Copy of Heating effect of electric current (1).gslides',
 "Copy of OHM'S LAW.pptx.gslides",
 'Copy of Daily Lesson -2 (1) (1).gslides',
 'Copy of Daily Lesson -2 (1).gslides',
 'Copy of Heating effect of electric current.gslides',
 'Copy of DL-PHY-MODULE 7- RESISTORS IN PARALLEL.gslides',
 'Aditi Raj-10J-22Oct-ComputerPT2.pdf',
 'Aditi Raj-10J-Social-PT2-25Oct.pdf',
 'AditiRaj-10J-Hindi-PT2-Oct27.pdf',
 'Real Numbers.pdf',
 'New Document(1).pdf',
 'Untitled document (25).gdoc',
 'MA',
 'Electricity Mind Map MA.jpg',
 'Physics Hw April 20.pdf',
 'India Map Latest.jpg',
 'Aditi Raj-Ma-Bio-8 November.pdf',
 'AditiRaj-10J-Chem-MA.pdf',
 'Untitled document (24).gdoc',
 'Untitled presentation (2).gslides',
 'Helen · SlidesCarnival.gslides',
 'Social Compiled DI .gdoc',
 'MAP FILE.pdf',
 'AditiRaj-10J-Physics-MA4.pdf',
 'MA Chem.pdf',
 'Map file part 2.pdf',
 'MAPFILE COVER PAGE AND INDEX.pdf',
 'MEP ADITI RAJ SUBJECTIVE 26 NOV.pdf',
 'Untitled8 (1).png',
 'art_.png',
 'n.jpg',
 'Untitled9 (1).png',
 'Untitled document - Pie chart 1.gsheet',
 'MEP WINTER PROJECT.gdoc',
 'MacBook Download',
 'Aditi Raj Maths Cycle Test.pdf',
 'ISA Phy.pdf',
 'Aditi Raj 10J English Cycle Test.pdf',
 'BIO SKILL TEST 4.gdoc',
 'CHEM IHS PSS 3.gdoc',
 'Tree House.pdf',
 'Aditi Raj 10J Cycle Test Social.pdf',
 'Untitled document (23).gdoc',
 'Untitled document (22).gdoc',
 'BIO SKILL TEST 5.gdoc',
 'Untitled document (21).gdoc',
 'BIO SKILL TEST 7.gdoc',
 'BIO SKILL TEST 8.gdoc',
 'night ocean.jpg',
 'Math 10th Paper-7.pdf',
 'Math 10th Paper-7 (1).gdoc',
 'Math 10th Paper-7.gdoc',
 'Chem Skill Based Test.gdoc',
 'SC Phy 28 July 3rd Period.gdoc',
 '11th & 12th Math CBSE se JEE tak.gdoc',
 'JEE Mathematics Reference.gdoc',
 'My Performance.gsheet',
 'HA ✓.gdoc',
 'd.png',
 's.png',
 'g.png',
 'Untitled7.png',
 'Untitled8.png',
 'Untitled9.png',
 'Aadhar Aditi Raj.jpg',
 'Aditi Raj Photo.jpg',
 '10th Marksheet.pdf',
 'RajKPrasad Photo.jpg',
 'GK Passport Photo.jpg',
 'TC Aditi Raj.jpg',
 'EB Vector.png',
 'ykw.png',
 'Untitled29_20211018142156.png',
 'sigh.png',
 '06 Humsafar (Alia Bhatt Version) 190Kbps.mp3',
 '07 Aayat (Bajirao Mastani)  - Arijit Singh 192Kbps.mp3',
 'Bas Itna Hai Kehna-(Mr-Jatt.com).mp3',
 'Chhoti Si Umar-Various__Raag.Me__.mp3',
 'Dangal (128 Kbps) - Pritam - Daler Mehndi-1.mp3',
 'Dangal (128 Kbps) - Pritam - Daler Mehndi.mp3',
 'Dhaakad (128 Kbps; Dangal) - Raftaar - Pritam.mp3',
 'Ek Pyar Ka Nagma Hai-(Mr-Jatt.com).mp3',
 'Gilehriyaan (128 Kbps; Dangal) - Jonita Gandhi-1.mp3',
 'Haanikaarak Bapu (128 Kbps; Dangal) - Pritam - Sarwar Khan - Sartaz Khan Barna-1.mp3',
 'Jane-Woh-Kaise-Log-The-(RaagSong.Com).mp3',
 'Main Rahoon Ya Na Rahoon - Armaan Malik - ClickMaza.com (1).mp3',
 'Naina (320 Kbps) (Dangal) - Arijit Singh.mp3',
 'Piya Aiso Jiya Mein (Sahib Bibi Aur Ghulam) @ IndiaMp3.com.mp3',
 'Tujhse_Naraz_Nahin_Zindagi-Lata_Mangeshkar[www.Mp3MaD.Com].mp3',
 'Tum-Mujhe-Yun-Bhula-Na-Paoge-Female (SongsMp3.Com).mp3',
 'Waqt_Ne_Kiya_Kya_Haseen_Sitam-Geeta_Dutt[www.Mp3MaD.Com].mp3',
 'Nahi Saamne Ye Alag Baat Hai (RaagJatt.com).mp3',
 'Chemical Bonding_Sheet.pdf',
 'Chemical Bonding_Sheet_XII (1).pdf',
 'Bio Task.jpg',
 'Phy Graph.jpg',
 'Practise.gdoc',
 'AditiRaj-May27-RevisionTest.pdf',
 'Gr 10- How do organisms reproduce- Revision Answers.gdoc',
 'Resistance from Graph .jpg',
 '20200319_073353.jpg',
 'Answers HTML Practise.gdoc',
 'Computer MA.gdoc',
 'AditiRaj-Comp-MA2-28May.gdoc',
 'tbe.png',
 'Untitled32.png',
 'Aditi Raj - DA - The Midnight Visitor - Copy (1).docx',
 'Aditi Raj - SS RA 2 Revision Worksheet   New-Gr 10(2020-21).doc',
 'Aditi Raj - Round square activity.docx',
 'AditiRaj-ExtractionOfHighlyReactiveMetals-Chem MA.gdoc',
 'Aditi Raj - GR 10 - MODULE 3-READING ACROSS CURRICULUM 2 (1).docx',
 'Aditi Raj - AS Revision Assignment Gr 10 (RA 2).docx',
 'Aditi Raj - Gr 10 Political Science Reinforcement  7.4.20.docx',
 'Aditi Raj - SS RA 2 Revision Worksheet  Gr 10(2020-21) (1).doc',
 'Aditi Raj - Asynch Module grade10 (1).docx',
 'Aditi Raj - Activity Gr 10 (1).docx',
 'SCIENTIFIC ENQUIRY-Aditi Raj.docx',
 'Aditi Raj - Gr. 10 English Worksheet.docx',
 'Aditi Raj - C ritical Reading Grade9.docx',
 'Aditi Raj - Activity Gr 10.docx',
 'Untitled document (20).gdoc',
 '..gdoc',
 'nansie forgot my birthday.gdoc',
 'blah.gdoc',
 'Aditi Raj - Group-E task_Early attempts of classification.docx',
 'Chemical Bonding_Sheet_XII.pdf',
 'nc',
 'OC-1.pdf',
 'Periodic Table.pdf',
 'COM.pdf',
 'IOC_Metallurgy_E.pdf',
 'Surface Chemistry .pdf',
 'Document from Aditi Raj.pdf',
 'FINAL_Binomial Theorem_Th+Ex.pdf',
 'FINAL_Permtation and Comb_Th+Ex.pdf',
 'Mole.pdf',
 'Redox.pdf',
 'Phy Notes',
 'Sanjeev Garg - Aakash-IIT- JEE( question +ans).pdf',
 '43 Chem.pdf',
 'Three Dimensional Geometry .pdf',
 'Copy of Notes - #2271 Irina.gsheet',
 'Copy of IT_Project_Classroom_Announcement_A4 (1).gdoc',
 'Meeting notes.gdoc',
 'Photo from Aditi Raj',
 'Copy of IT_Project_Classroom_Announcement_A4.gdoc',
 'Unc. Study Stuff ',
 'Untitled document (19).gdoc',
 'Untitled document (18).gdoc',
 'Untitled document.pdf',
 '240310272268_ApplicationForm.pdf',
 'Untitled document (17).gdoc',
 'Flash cards.gslides',
 'Untitled presentation (1).gslides',
 'Drawing For Dummies (For Dummies (Sports & Hobbies)) ( PDFDrive ).pdf',
 'Untitled document (16).gdoc',
 'Untitled spreadsheet (17).gsheet',
 'IIITs.gsheet',
 'FHjV1hrVgAExKMt.jpeg',
 'Untitled spreadsheet (16).gsheet',
 'IIIT 2023 Cut Off.xlsx',
 'Untitled spreadsheet (15).gsheet',
 'Untitled spreadsheet (14).gsheet',
 'Final Choices (1).xlsx',
 'Final Choices.xlsx',
 'Copy of Final Choices.xlsx',
 'Untitled spreadsheet (13).gsheet',
 'Untitled spreadsheet (12).gsheet',
 'night ocean (darkened).jpg',
 'babies.jpg',
 'My-ID-Card.pdf',
 'Electronic Devices and Circuit Theory - 11th Edition.pdf',
 'Microelectronic Circuits by SedraSmith.pdf',
 'ec lab.pdf',
 '10689.19608_text_removed.pdf',
 'Assassins_Apprentice-Robin Hobb.epub',
 'Head First HTML and CSS_ A Learner’s Guide to Creating Standards-Based Web Pages ( PDFDrive ).pdf',
 'Untitled document (15).gdoc',
 'Lab Manual Sem 2.pdf',
 'CO Textbook Ch-4.pdf',
 'CO Appendix B.pdf',
 'fluent.mp3',
 'musicpfp.jpg',
 'Untitled document (14).gdoc',
 'Untitled document (13).gdoc',
 'Lab 1: 2024BCS0148 Aditi Raj.gdoc',
 'LAB 2: 2024BCS0148 Aditi Raj.gdoc',
 'LAB 1: Excercise 2024BCS0148 Aditi Raj.gdoc',
 'student.gdoc',
 'Lab 1: Flat File: 2024BCS0148 Aditi Raj.gdoc',
 'Adobe Scan 14 Aug 2025_1 (1).jpg',
 'Lab1 Practice Problem 2024BCS0148 Aditi Raj.gdoc',
 'LAB3 Manhatten Distance Aditi Raj 2024BCS0148.gdoc',
 'Tutuorial 1 IT Workshop III.gdoc',
 'ICS214 LAB 3: Aditi Raj 2024BCS0148.gdoc',
 'Tutorial Exercises 20 Aug: 2024BCS0148 Aditi Raj .gdoc',
 'LAB 4 Collinear Check: 2024BCS0148 Aditi Raj.gdoc',
 'LAB 4 Extra Exercises: 2024BCS0148 Aditi Raj.gdoc',
 'Tutorial Exercises 27 08 : 2024bcs0148 Aditi Raj.gdoc',
 'back exc.gslides',
 'IMG_20250430_121842.jpg',
 'iris (in rain).mp3',
 'Untitled document (12).gdoc',
 'Untitled document (11).gdoc',
 'Untitled spreadsheet (11).gsheet',
 'Untitled document (10).gdoc',
 'Untitled document (9).gdoc',
 'ICS 214 Tutorial (10Sep25): 2024BCS0148 Aditi Raj.gdoc',
 'ICS 211 Assignment 1 Answers.pdf',
 'Untitled presentation.gslides',
 'Screenshot_20251012_141142_Drive.png',
 'TOC last pages.pdf',
 'Untitled spreadsheet (10).gsheet',
 'Untitled spreadsheet (9).gsheet',
 'Untitled document (8).gdoc',
 'Untitled document (7).gdoc',
 'Untitled document (6).gdoc',
 '20260102_195021 (1).jpg',
 '20260102_195021.jpg',
 '20260102_195030.jpg',
 'Untitled spreadsheet (8).gsheet',
 'Untitled spreadsheet (7).gsheet',
 'leet.gsheet',
 'Untitled spreadsheet (6).gsheet',
 'Untitled spreadsheet (5).gsheet',
 'Untitled document (5).gdoc',
 'Untitled document (4).gdoc',
 'linkedlin.jpeg',
 'Untitled spreadsheet (4).gsheet',
 'Untitled document (3).gdoc',
 'Untitled document (2).gdoc',
 'Untitled spreadsheet (3).gsheet',
 'Indian_Fresher_Salary_Skills_2025 (1).gsheet',
 'NaukriData_Data Science.gsheet',
 'Indian_Fresher_Salary_Skills_2025.gsheet',
 'Colab Notebooks',
 'Untitled spreadsheet (2).gsheet',
 "don't forget.gsheet",
 'Resume (1).pdf',
 'meow.gsheet',
 'Untitled spreadsheet (1).gsheet',
 'Untitled document (1).gdoc',
 '20260802_183650.mp4',
 'Untitled spreadsheet.gsheet',
 'Untitled document.gdoc',
 'anki wallpaper.jpg',
 'Aditi Raj - Asynch Module grade10.docx',
 'Aditi Raj - GR 10 - MODULE 3-READING ACROSS CURRICULUM 2.docx',
 'Aditi Raj - DA - The Midnight Visitor - Copy.docx']

In [4]:
os.listdir('/content/drive/MyDrive/Job Market Project/data')

['indian-job-market-dataset-2025.xlsx',
 'indian-job-market-dataset-2025.gsheet']

In [5]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Job Market Project/data/indian-job-market-dataset-2025.xlsx')


# Dataset Quality

## Missing and Duplicates:

In [6]:
#understand the dimensions of data, what is missing, how many rows are duplicate

print("Shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)

Shape: (97929, 17)

Missing values:
title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

Duplicate rows: 247

Data types:
title                 object
jobId                  int64
currency              object
jobUploaded           object
companyName           object
tagsAndSkills         object
experience            object
salary                object
location              object
companyId              int64
ReviewsCount         float64
AggregateRating      float64
jobDescription        object
minimumSalary        float64
maximumSalary        float64
minimumExperience    float64
maximumExperience    float64
dtype: object

In [ ]:
# so the different columns I need to check: skills, experience, salary, locations, reviews, rating, job uploaded

In [7]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  object
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  object
 3   jobUploaded        97929 non-null  object
 4   companyName        97925 non-null  object
 5   tagsAndSkills      97358 non-null  object
 6   experience         95824 non-null  object
 7   salary             97929 non-null  object
 8   location           97929 non-null  object
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  object
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 12.7+ MB

In [8]:
# checking null values again
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(247)

In [9]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
97924    False
97925    False
97926    False
97927    False
97928    False
Length: 97929, dtype: bool

In [10]:
missing = (df.isnull().sum() / len(df)*100).sort_values(ascending=False)

print(missing)

AggregateRating      35.997508
ReviewsCount         35.997508
experience            2.149516
minimumSalary         0.583075
tagsAndSkills         0.583075
maximumExperience     0.583075
maximumSalary         0.583075
minimumExperience     0.583075
companyName           0.004085
title                 0.000000
location              0.000000
currency              0.000000
jobUploaded           0.000000
jobId                 0.000000
salary                0.000000
jobDescription        0.000000
companyId             0.000000
dtype: float64

## Skills:

In [11]:
skills = df['tagsAndSkills'].dropna().str.split(',').explode().str.strip()
print("Total skill mentions:", len(skills))
print("\nTop 20 skills:")
print(skills.value_counts().head(20))

Total skill mentions: 755421

Top 20 skills:
tagsAndSkills
Sales                   6480
Management              4856
project management      3972
python                  3962
css                     3789
Development             3283
sap                     3202
sales                   2726
Communication Skills    2523
c#                      2423
English                 2249
sql                     2206
Automation              2200
customer service        2168
java                    2158
Customer Service        1968
Analytical              1944
business development    1924
Java                    1913
Python                  1894
Name: count, dtype: int64

In [12]:
print("\nUnique skills:", skills.nunique())
#checking capitalization issues
print("\nSample - same skill different cases:")
print(skills[skills.str.lower() == 'python'].value_counts())

Unique skills: 59479

Sample - same skill different cases:
tagsAndSkills
python    3962
Python    1894
PYTHON       4
Name: count, dtype: int64

## Locations:

In [13]:
print("Unique locations:", df['location'].nunique())
print("\nTop 20 locations:")
print(df['location'].value_counts().head(20))

Unique locations: 10066

Top 20 locations:
location
Bengaluru                        16823
Hyderabad                         7669
Pune                              6112
Chennai                           4431
Gurugram                          4233
Mumbai                            4157
Noida                             2695
Remote                            1961
Ahmedabad                         1726
Navi Mumbai                       1453
Kolkata                           1049
Hyderabad, Chennai, Bengaluru     1037
Hybrid - Bengaluru                 946
Jaipur                             821
Coimbatore                         618
Hybrid - Hyderabad                 576
Kochi                              528
Vadodara                           528
Hybrid - Pune                      480
Thane                              410
Name: count, dtype: int64

In [14]:
remote = df[df['location'].str.contains('Remote', case=False, na=False)]
hybrid = df[df['location'].str.contains('Hybrid', case=False, na=False)]
multi = df[df['location'].str.contains(',', na=False)]
print(f"\nRemote jobs: {len(remote)}")
print(f"Hybrid jobs: {len(hybrid)}")
print(f"Multi-city jobs: {len(multi)}")

Remote jobs: 1967
Hybrid jobs: 5765
Multi-city jobs: 19300

In [25]:
df['location'].isna().any()

np.False_

# Salary:

In [15]:
total = len(df)
disclosed = (df['minimumSalary'] != 0).sum()
print(f"Disclosed: {disclosed} ({round(disclosed/total*100, 1)}%)")
print(f"Undisclosed: {total - disclosed} ({round((total-disclosed)/total*100, 1)}%)")

Disclosed: 33800 (34.5%)
Undisclosed: 64129 (65.5%)

In [18]:
#distribution of disclosed salaries
disclosed_df = df[df['minimumSalary'] != 0]
print("Salary distribution of disclosed:")
print(disclosed_df['minimumSalary'].describe())

Salary distribution of disclosed:
count    3.322900e+04
mean     5.810282e+05
std      8.425478e+05
min      7.860000e+02
25%      2.000000e+05
50%      3.000000e+05
75%      6.000000e+05
max      7.000000e+07
Name: minimumSalary, dtype: float64

In [ ]:
print(df['maximumSalary'].max())
print(df['minimumSalary'].max())

95000000.0
70000000.0

In [19]:
#check outliers
print("Top 10 highest minimum salaries:")
print(disclosed_df['minimumSalary'].sort_values(ascending=False).head(10))

Top 10 highest minimum salaries:
89340    70000000.0
4048     20000000.0
4115     20000000.0
64394    17500000.0
9484     10000000.0
74028    10000000.0
42231    10000000.0
6226     10000000.0
44891     9600000.0
44617     9000000.0
Name: minimumSalary, dtype: float64

## Experience:

In [20]:
print("Experience range sample:")
print(df['experience'].value_counts().head(20))
print(df['experience'].describe())

Experience range sample:
experience
5-10 Yrs     6448
3-8 Yrs      5767
1-3 Yrs      3919
2-5 Yrs      3779
1-6 Yrs      3632
2-7 Yrs      3615
0-5 Yrs      3293
3-5 Yrs      3290
5-8 Yrs      3268
4-9 Yrs      2876
1-5 Yrs      2867
0-1 Yrs      2584
1-4 Yrs      2423
6-11 Yrs     2386
0-2 Yrs      2310
2-4 Yrs      2264
7-12 Yrs     2202
8-13 Yrs     2130
3-6 Yrs      2126
15-20 Yrs    1952
Name: count, dtype: int64
count        95824
unique         287
top       5-10 Yrs
freq          6448
Name: experience, dtype: object

In [21]:
print("Minimum experience distribution:")
print(df['minimumExperience'].describe())
print("\nMaximum experience distribution:")
print(df['maximumExperience'].describe())

Minimum experience distribution:
count    97358.000000
mean         3.957744
std          3.581196
min          0.000000
25%          1.000000
50%          3.000000
75%          5.000000
max         30.000000
Name: minimumExperience, dtype: float64

Maximum experience distribution:
count    97358.000000
mean         7.732647
std          4.500161
min          0.000000
25%          5.000000
50%          7.000000
75%         10.000000
max         35.000000
Name: maximumExperience, dtype: float64

In [24]:
#check outliers
print("Jobs requiring 20+ years:")
print((df['minimumExperience'] >= 20).sum())

print(df['minimumExperience'].isna().sum())

print(df['maximumExperience'].isna().sum())

Jobs requiring 20+ years:
209
571
571

In [ ]:
# count of missing values in the experience column
print(df['experience'].isna().sum())

2105

In [ ]:
df[df['minimumExperience'] == 0][
    ['experience', 'minimumExperience', 'maximumExperience']
].sample(20)

      experience  minimumExperience  maximumExperience
11998    0-1 Yrs                0.0                1.0
51972    0-1 Yrs                0.0                1.0
95499    0-1 Yrs                0.0                1.0
15566    0-3 Yrs                0.0                3.0
85997      0 Yrs                0.0                0.0
964      0-5 Yrs                0.0                5.0
67759    0-1 Yrs                0.0                1.0
48988    0-4 Yrs                0.0                4.0
90150    0-2 Yrs                0.0                2.0
94468    0-2 Yrs                0.0                2.0
44352    0-1 Yrs                0.0                1.0
970      0-5 Yrs                0.0                5.0
97287    0-3 Yrs                0.0                3.0
81623    0-1 Yrs                0.0                1.0
72406    0-5 Yrs                0.0                5.0
82992    0-3 Yrs                0.0                3.0
56660    0-1 Yrs                0.0                1.0
6162     0-5 Yrs                0.0                5.0
11950    0-1 Yrs                0.0                1.0
24301    0-2 Yrs                0.0                2.0

In [ ]:
df[
    (df['minimumExperience'] == 0) &
    (df['experience'].isna())
][['experience', 'minimumExperience', 'maximumExperience']].head(20)

    experience  minimumExperience  maximumExperience
211        NaN                0.0                1.0
217        NaN                0.0                1.0
296        NaN                0.0                4.0
390        NaN                0.0                4.0
404        NaN                0.0                3.0
405        NaN                0.0                1.0
446        NaN                0.0                1.0
492        NaN                0.0                1.0
504        NaN                0.0                1.0
533        NaN                0.0                5.0
567        NaN                0.0                2.0
573        NaN                0.0                5.0
574        NaN                0.0                5.0
598        NaN                0.0                4.0
638        NaN                0.0                0.0
658        NaN                0.0                2.0
682        NaN                0.0                5.0
690        NaN                0.0                5.0
704        NaN                0.0                3.0
818        NaN                0.0                2.0

## Title, Company Name:

In [ ]:
df['title'].nunique()

55104

In [ ]:
df['companyName'].nunique()

18668

In [ ]:
df['title'].value_counts().head(30)

title
Application Developer             2039
Application Lead                  1347
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     457
Trust & Safety New Associate       348
Data Engineer                      339
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          283
Java Developer                     253
Relationship Manager               232
Area Sales Manager                 219
Application Support Engineer       217
Accountant                         215
Customer Support Executive         213
Senior Software Engineer           207
Account Executive                  205
Graphic Designer                   191
Software Development Lead          181
Business Development Associate     177
Business Analyst                   172
Software Engineer                  165
Technical Lead - L1                165
AI / ML Engineer                   153
Sales Officer Home Loan            152
Developer - L3                     143
Customer Care Executive            137
Field Sales Executive              131
Project Manager                    124
Name: count, dtype: int64

In [ ]:
df['companyName'].value_counts().head(20)

companyName
Accenture                                         8204
IDESLABS PRIVATE LIMITED                          2303
Wipro                                             1496
Krazy Mantra HR Solutions Pvt. Ltd                1028
Kotak Mahindra Bank                                987
PRO Hr Complete Solutions                          982
Infosys                                            938
Capgemini                                          700
IBM                                                687
PRADEEPIT CONSULTING SERVICES PVT LTD              618
Talent21                                           613
HR Innovation Group                                607
Vision Beyond Resources India Private Limited      582
EY                                                 571
Gratitude India Manpower Consultants Pvt. Ltd.     567
Axis Bank                                          547
ABB                                                428
Essentiallysports                                  422
Purview India Consulting And  Services  Llp        399
eClerx                                             389
Name: count, dtype: int64

## Rating:

In [ ]:
df.groupby('companyName')['AggregateRating'].nunique().describe()

count    18668.000000
mean         0.590583
std          0.495862
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: AggregateRating, dtype: float64

In [ ]:
(
    df.groupby('companyName')['AggregateRating']
      .nunique()
      .value_counts()
      .sort_index()
)

AggregateRating
0     7681
1    10949
2       38
Name: count, dtype: int64

In [ ]:
df['AggregateRating'].isna().sum()

np.int64(35252)

## Else:

In [ ]:
df['currency'].value_counts()

currency
INR    97800
USD      129
Name: count, dtype: int64

In [ ]:
df['jobDescription'].isna().any()

np.False_

In [27]:
df.groupby('companyId')['companyName'].nunique().sort_values(ascending=False).head()

companyId
6796003    55
759377     12
6234166     9
5670632     8
2585064     7
Name: companyName, dtype: int64